events {
    worker_connections 256;
}

http {
    upstream kv_carts_nodes {
        server kv-carts-node1:8085;
        server kv-carts-node2:8085;
        server kv-carts-node3:8085;
    }

    server {
        listen 8085;

        location / {
            proxy_pass http://kv_carts_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 5s;
            proxy_read_timeout 15s;
        }
    }
}
